import Head from 'next/head'
import Image from 'next/image'
import { Inter, Nunito } from 'next/font/google'
import { signIn } from 'next-auth/react'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
            Not signed in <br />
            <button onClick={() => signIn('google', {
              callbackUrl: '/dashboard'
            })}>Sign in</button>  
      </main>
    </>
  )
}




