import Head from 'next/head'
import {FcGoogle} from 'react-icons/fc'
import { signIn } from 'next-auth/react'
import styles from './signIn/signIn.module.css'

import { nunito } from './_app'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.signInPage}>
            <button className={nunito.className} onClick={() => signIn('google', {
              callbackUrl: '/dashboard'
            })}>
              <FcGoogle size={25}/>
              Entrar com o Google</button>  
      </main>
    </>
  )
}




